### ISSUE TITLE
Test setup: conditionally skip type tests

### ISSUE THREAD

**Issue by SevInf** [prisma/client-planning#65]
Right now, different types might be generated for different clients. Occasionally, it would mean that some method might not be available for all providers (i.e. `$queryRaw` for mongodb). It is possible to conditionally skip test execution with `testIf`, but it still will be typechecked and fail. We should we have a way to conditionally skip type tests.

## Option 1: magic comments

```ts
// @ts-ignore-if: provider === "mongodb"
prisma.$queryRaw`...`
```

When we copy the files, we will then scan the sources for `@ts-ignore-if` comments, evaluate the condition and if it is true, turn the comment into `// @ts-ignore`, leave it as it is otherwise.

- \+ very little boilerplate
- \+ flexible enough to support more complex conditions
- \+ symmetrical with `testIf`
- \- "magical comments" are not easy to understand/debug
- \- can get cumbersome if we need to skip a lot of typechecks (on other hand,  if we use `@ts-expect-error` instead of `ts-ignore` this can be used as a test that calling missing method on unsupported provider is a compile time error)

## Option 2: file suffixes

Along with `tests.ts` file, have an option to have `tests.<provider>.ts` which will be copied only into corresponding providers generated test directory, thus executing typechecks only where it is needed. We could also have suffixes for the groups of providers, say `tests.sql.ts` for all SQL databases. For example, if we have following files in the sources:

- tests.ts
- tests.sql.ts
- tests.postgresql.ts 
 
 when running with postgres provider, all 3 tests will be executed and typechecked. When running with mongodb provider, only `tests.ts` will execute and typecheck
 
 - \+ can skip typechecks for large amounts of code at once
 - \+ it is clear from the files structure that some of the tests are provider specific
 - \- a lot of motions necessary if we want to move a single test out of main test files
 - \- more complicated conditions are not possible: what if we want to run tests and typechecks only for 2 out of sql providers? What if we want to use matrix parameters, other than `provider`?
  - \- no actual verification that code that skips type checks has any type errors in them

## Option 3: do nothing, split tests with different types into different suites manually

Essentialy, option 2, but done manually with all advantages and disadvantages.

**Comment by danstarns** [comment]
I feel that **Option 1: magic comments** would be the simplest and +1 for this! Option 2 means we could potentially end up with X amount of files per test and repeated code. For Option 1, would we have to pre-compile the files and edit the ast?

**Comment by SevInf** [comment]
I think, for now we can do with regex replace (famous last words) and evaluate everything after `:` with `suiteConfig` as the context. We already do some simple pre-processing for import path adjustments when copying files over, this one should be similar.

**Comment by danstarns** [comment]
> I think, for now we can do with regex replace (famous last words) and evaluate everything after `:` with `suiteConfig` as the context. We already do some simple pre-processing for import path adjustments when copying files over, this one should be similar.

Do you think this would slow down the test suite?

**Comment by SevInf** [comment]
I don't think it will have that big impact of the performance,  but we can always measure. If it will, we can then think of either falling back on option 2 or maybe some different approach to the transform for option 2 in general.

**Comment by danstarns** [comment]
Option 1 for me then!

**Comment by danstarns** [comment]
Bearing in mind we might need more complex boolean logic like: 

```
provider === "mongodb" || "postgresql" 
```
